### ISSUE TITLE
Implement Exchange.readtree and Exchange.writetree

### ISSUE THREAD

**Issue by Lawrence37** [LibreTexts/nbgrader-to-jupyterlab#1]
Exchange.readtree and Exchange.writetree will be used in place of shutil.copytree. readtree recursively reads files (not including ignored files) from a source directory and converts it to an [encoded directory tree](https://github.com/lxylxy123456/ngshare/blob/master/api-specifications.md#directory-tree). writetree writes files (not including ignored files) from an encoded directory tree to the destination directory.

**Comment by aalmanza1998** [comment]
closing this issue. I implemented `encode_dir` and `decode_dir` in the base `Exchange` class to have this functionality.
