### ISSUE TITLE
A small fix seems needed. 

### ISSUE THREAD

**Issue by sdyang1729** [LibreTexts/nbgrader-to-jupyterlab#10]
### Operating system
mac os Catalina 10.15.4

### `nbgrader --version`
0.7.0.dev

### `jupyterhub --version` (if used with JupyterHub)
N/A

### `jupyter notebook --version` 
6.0.3

### Actual behavior
As of 06/10/2020, when I try to install the https://github.com/LibreTexts/nbgrader-to-jupyterlab/tree/lab-common branch, the following error message appears when executing  jupyter lab.
```
nbgrader-to-jupyterlab/nbgrader/labextensions/assignment_list/assignment_list/handlers.py", line 357, in setup_handlers
        lab_app.web_app.settings[url] = AssignmentList(parent=lab_app)
      File "/opt/anaconda3/envs/nbgradertest2/lib/python3.8/site-packages/traitlets/config/configurable.py", line 67, in __init__
        kwargs['config'] = parent.config
    AttributeError: 'NotebookWebApplication' object has no attribute 'config'
```

### My Solution
I had to change the line 19 of the nbgrader/labextensions/assignment_list/assignment_list/__init__.py  from "setup_handlers(lab_app.web_app)" to "setup_handlers(lab_app)".  Then it works as expected.

I hope this is of some help to those who try to install this branch.

**Comment by Lawrence37** [comment]
@aalmanza1998 Is the proposed solution correct?

**Comment by aalmanza1998** [comment]
> @aalmanza1998 Is the proposed solution correct?

yes, I checked the handlers.py file and the setup requires `lab_app` not a `lab_app.web_app`
